### ISSUE TITLE
Release 4.3.0 breaks the Rpush initialization

### ISSUE THREAD

**Issue by vzamanillo** [rpush/modis#50]
rel https://github.com/rpush/modis/pull/49

![image](https://github.com/user-attachments/assets/30e217cc-7003-48c9-847f-154572adcf81)

We can no longer initialize rpush in the old way 

```
  # Options passed to Redis.new
  # config.redis_options = {}
```

The following initialization example (old way) raises a `NoMethodError`

`config.redis_options = { url: Rails.application.config.redis_urls[:default_db] }`

because it's expecting the `:default` key, this way

`config.redis_options[:default] = { url: Rails.application.config.redis_urls[:default_db] }`

**Comment by benlangfeld** [comment]
4.3.1 released, please try with that version.
